language: node_js
node_js:
  - '6'
  - '4'
  - '5'
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - yarn
after_success:
  - yarn coverage:report
  - bash <(curl -s https://codecov.io/bash)
